#!/usr/bin/env python3
"""Compare original vs phase19 runtime screenshots generated by headless tests."""
from __future__ import annotations

import csv
import json
from pathlib import Path
from PIL import Image, ImageChops

ROOT = Path(__file__).resolve().parents[1]
ORIG = ROOT / "playtest_output" / "phase19_original"
MOD = ROOT / "playtest_output" / "phase19_gateway"
OUT = ROOT / "playtest_output" / "phase19_original_compare.csv"
DOC = ROOT / "docs" / "PHASE19_RUNTIME_COMPARE.md"


def changed_pixels(a: Path, b: Path) -> int:
    ia = Image.open(a).convert("RGBA")
    ib = Image.open(b).convert("RGBA")
    diff = ImageChops.difference(ia, ib)
    if diff.getbbox() is None:
        return 0
    return sum(1 for px in diff.getdata() if px != (0, 0, 0, 0))


def main() -> None:
    rows = []
    for a in sorted(ORIG.glob("screenshot-*.png")):
        b = MOD / a.name
        if not b.exists():
            continue
        rows.append({"original": a.relative_to(ROOT).as_posix(), "phase19": b.relative_to(ROOT).as_posix(), "changed_pixels": changed_pixels(a, b)})
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", newline="", encoding="utf-8") as fp:
        writer = csv.DictWriter(fp, fieldnames=["original", "phase19", "changed_pixels"])
        writer.writeheader()
        writer.writerows(rows)
    changed = sum(1 for r in rows if r["changed_pixels"])
    lines = [
        "# Phase 19 runtime compare",
        "",
        f"Compared screenshots: {len(rows)}",
        f"Screenshots with changes: {changed}",
        "",
        f"CSV: `{OUT.relative_to(ROOT)}`",
        "",
    ]
    if changed == 0:
        lines.append("Result: PASS — phase19 gateway payload preserves the captured original early experience pixel-for-pixel.")
    else:
        lines.append("Result: differences detected; inspect CSV before using this build as original-first.")
    DOC.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    print(f"Wrote {DOC.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
