#!/usr/bin/env python3
"""Convert a PNG/JPEG into a 240x160 indexed Mode 4 C header.

Usage:
    python3 tools/png_to_mode4.py new_assets/GOKU.png \
        --output include/custom_asset.h --preview data/custom_asset.png

Mode 4 is an 8-bit indexed framebuffer: the resulting image has exactly
240*160 bytes followed by 256 GBA BGR555 palette words. This utility is for
standalone libgba assets; it does not locate or overwrite data in a commercial
ROM.
"""
from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageOps

WIDTH = 240
HEIGHT = 160


def gba_color(rgb: tuple[int, int, int]) -> int:
    r, g, b = rgb
    return ((r >> 3) & 0x1F) | (((g >> 3) & 0x1F) << 5) | (((b >> 3) & 0x1F) << 10)


def convert(source: Path) -> Image.Image:
    image = Image.open(source).convert("RGBA")
    # Transparent pixels use the first palette entry (black), matching the
    # common GBA convention for a Mode 4 background conversion.
    canvas = Image.new("RGBA", (WIDTH, HEIGHT), (0, 0, 0, 255))
    fitted = ImageOps.contain(image, (WIDTH, HEIGHT), method=Image.Resampling.NEAREST)
    x = (WIDTH - fitted.width) // 2
    y = (HEIGHT - fitted.height) // 2
    canvas.alpha_composite(fitted, (x, y))
    return canvas.convert("RGB")


def make_palette(image: Image.Image) -> list[tuple[int, int, int]]:
    quantized = image.quantize(colors=256, method=Image.Quantize.MEDIANCUT)
    raw = quantized.getpalette()[: 256 * 3]
    palette = [tuple(raw[i : i + 3]) for i in range(0, len(raw), 3)]
    palette += [(0, 0, 0)] * (256 - len(palette))
    return palette[:256]


def convert_to_indexed(image: Image.Image, palette: list[tuple[int, int, int]]) -> bytes:
    palette_image = Image.new("P", (16, 16))
    flat = [component for color in palette for component in color]
    palette_image.putpalette(flat)
    return image.quantize(palette=palette_image, dither=Image.Dither.NONE).tobytes()


def write_header(path: Path, name: str, palette: list[tuple[int, int, int]], pixels: bytes) -> None:
    name = "".join(character if character.isalnum() else "_" for character in name)
    words = [gba_color(color) for color in palette]
    with path.open("w", encoding="utf-8") as handle:
        handle.write("/* Generated by tools/png_to_mode4.py. */\n")
        handle.write(f"#ifndef {name.upper()}_H\n#define {name.upper()}_H\n\n")
        handle.write(f"#define {name.upper()}_WIDTH 240\n#define {name.upper()}_HEIGHT 160\n\n")
        handle.write(f"static const unsigned short {name}_palette[256] __attribute__((aligned(4))) = {{\n")
        for start in range(0, 256, 8):
            values = ", ".join(f"0x{word:04X}" for word in words[start : start + 8])
            handle.write(f"    {values}{',' if start + 8 < 256 else ''}\n")
        handle.write("};\n\n")
        handle.write(f"static const unsigned char {name}_bitmap[240 * 160] __attribute__((aligned(4))) = {{\n")
        for start in range(0, len(pixels), 24):
            values = ", ".join(str(value) for value in pixels[start : start + 24])
            handle.write(f"    {values}{',' if start + 24 < len(pixels) else ''}\n")
        handle.write("};\n\n#endif\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--preview", type=Path)
    parser.add_argument("--name", default="custom_asset")
    args = parser.parse_args()

    image = convert(args.source)
    palette = make_palette(image)
    pixels = convert_to_indexed(image, palette)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    write_header(args.output, args.name, palette, pixels)
    if args.preview:
        args.preview.parent.mkdir(parents=True, exist_ok=True)
        image.save(args.preview)
    print(f"Wrote {args.output} ({len(pixels)} indexed pixels)")


if __name__ == "__main__":
    main()
